### ISSUE TITLE
All about the emojis

### ISSUE THREAD

**Issue by amirad** [MozillaFoundation/internet-health-report-2018-bugs#17] opened 2018-03-30 14:46 UTC
### Expected behaviour (How should it be)?
I couldn't find them when I was looking for them! 

Here's my comment from slack "So few things, we will need to tell people they have to sign in to see or add emojis? Can it be visible at all times? The way it's presented now makes me feel like I'm reacting to the whole report instead of the article?"

They should live at the bottom of the article so we know it is associated to it, they should also be visible without signing on, my preference would even be that you can emoji without signing in (maybe), and it should say 'how does this article make you feel'?"

Also, I can't un-click an emoji reaction once I've click it. 

...

### Actual behaviour (What is wrong)?
They are maybe not colourful and blend into the site? They are hidden until you sign in! And It doesn't say to use them to comment on the article which confuses me and since it follows me while I nav I feel like I am reacting to the whole site. 
...

### Steps to reproduce (What should I do to see the problem)?

...

### Which part of the website does it belong to (add link, if possible)?

...

/cc @kaodro

**Comment by kaodro** [comment] 2018-04-02 15:23
@solanasaurus I completely agree with Amira and would change the prompt to the suggested one "How does this article make you feel?". I would also whether color the sticky bar or "unsticky"-it and place it directly under the article. It happened to me many times I didn't notice it as it blends into the website really well (and I know it's there!). 

@Dhakelila FYI, if you or your team have suggestions how to make the emoji bar stand out more. Let's change once we agree on direction.

@Dhakelila Let's check the sign in issue, I can't reproduce it (I can add and remove emojis without signing in).

**Comment by Solanasaurus** [comment] 2018-04-03 08:13
I am logged out and able to add emojis too.

Changing the promt to something that refers directly to the article, and making the sticky bar colorful - or maybe it could flash a color, like a blink to attract attention - seems like the easiest fix, I agree.

Funnily enough, I think the reason we made it sticky was to make it easier to find than it resting at the bottom.

**Comment by dhakelila** [comment] 2018-04-03 11:40
Hi there! 

The idea was that everybody could add reactions even without sign-in. Just to encourage the use of this feature. 
Log-in is required just for commenting. 

Regarding how to improve the usability, let's wait for more opinions maybe and agree on how to improve it. :)

**Comment by kaodro** [comment] 2018-04-08 12:09
Fixed by adding an emoji bar at the end of the article

**Closed as completed by kaodro** 2018-04-08 12:09 UTC
Labels: bug, question, Vizzuality to fix
